//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVOLUCIONES
    {
        public int Id_Devoluciones { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Fecha { get; set; }
        public string Cambio { get; set; }
        public Nullable<int> Id_Factura { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Id_Producto { get; set; }
    
        public virtual FACTURAS FACTURAS { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
