//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURAS()
        {
            this.DEVOLUCIONES = new HashSet<DEVOLUCIONES>();
        }
    
        public int Id_Factura { get; set; }
        public Nullable<int> Venta_Id { get; set; }
        public string Fecha { get; set; }
        public string Direccion { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEVOLUCIONES> DEVOLUCIONES { get; set; }
        public virtual VENTAS VENTAS { get; set; }
    }
}
